In [1]:
# ============================================
# 1. IMPORT LIBRARIES
# ============================================

import pandas as pd

pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

In [4]:
# ============================================
# 2. LOAD DATASETS
# ============================================

recipes = pd.read_csv("recipes.csv")
reviews = pd.read_csv("reviews.csv")   

print("Datasets loaded successfully!\n")
print("Recipes Shape:", recipes.shape)
print("Reviews Shape:", reviews.shape)

Datasets loaded successfully!

Recipes Shape: (522517, 28)
Reviews Shape: (1401982, 8)

Data preview

In [6]:
print("===========================Recipes============================================ :\n")
print(recipes.head())
print("::::::::::::::::::::::::::review:::::::::::::::::::::::::::::::::::::::::::::: \n")
print(reviews.head())

===========================Recipes============================================ :

   RecipeId                               Name  AuthorId      AuthorName  \
0        38  Low-Fat Berry Blue Frozen Dessert      1533          Dancer
1        39                            Biryani      1567        elly9812
2        40                      Best Lemonade      1566  Stephen Little
3        41     Carina's Tofu-Vegetable Kebabs      1586         Cyclopz
4        42                       Cabbage Soup      1538       Duckie067

  CookTime PrepTime TotalTime         DatePublished  \
0    PT24H    PT45M  PT24H45M  1999-08-09T21:46:00Z
1    PT25M     PT4H   PT4H25M  1999-08-29T13:12:00Z
2     PT5M    PT30M     PT35M  1999-09-05T19:52:00Z
3    PT20M    PT24H  PT24H20M  1999-09-03T14:54:00Z
4    PT30M    PT20M     PT50M  1999-09-19T06:19:00Z

                                         Description  \
0  Make and share this Low-Fat Berry Blue Frozen ...
1  Make and share this Biryani recipe from Food.com.
2  This is from one of my  first Good House Keepi...
3  This dish is best prepared a day in advance to...
4  Make and share this Cabbage Soup recipe from F...

                                              Images  ... SaturatedFatContent  \
0  c("https://img.sndimg.com/food/image/upload/w_...  ...                 1.3
1  c("https://img.sndimg.com/food/image/upload/w_...  ...                16.6
2  c("https://img.sndimg.com/food/image/upload/w_...  ...                 0.0
3  c("https://img.sndimg.com/food/image/upload/w_...  ...                 3.8
4  "https://img.sndimg.com/food/image/upload/w_55...  ...                 0.1

  CholesterolContent SodiumContent CarbohydrateContent  FiberContent  \
0                8.0          29.8                37.1           3.6
1              372.8         368.4                84.4           9.0
2                0.0           1.8                81.5           0.4
3                0.0        1558.6                64.2          17.3
4                0.0         959.3                25.1           4.8

   SugarContent  ProteinContent  RecipeServings  RecipeYield  \
0          30.2             3.2             4.0          NaN
1          20.4            63.4             6.0          NaN
2          77.2             0.3             4.0          NaN
3          32.1            29.3             2.0     4 kebabs
4          17.7             4.3             4.0          NaN

                                  RecipeInstructions
0  c("Toss 2 cups berries with sugar.", "Let stan...
1  c("Soak saffron in warm milk for 5 minutes and...
2  c("Into a 1 quart Jar with tight fitting lid, ...
3  c("Drain the tofu, carefully squeezing out exc...
4  c("Mix everything together and bring to a boil...

[5 rows x 28 columns]
::::::::::::::::::::::::::review::::::::::::::::::::::::::::::::::::::::::::::

   ReviewId  RecipeId  AuthorId        AuthorName  Rating  \
0         2       992      2008         gayg msft       5
1         7      4384      1634     Bill Hilbrich       4
2         9      4523      2046  Gay Gilmore ckpt       2
3        13      7435      1773     Malarkey Test       5
4        14        44      2085        Tony Small       5

                                              Review         DateSubmitted  \
0       better than any you can get at a restaurant!  2000-01-25T21:44:00Z
1  I cut back on the mayo, and made up the differ...  2001-10-17T16:49:59Z
2  i think i did something wrong because i could ...  2000-02-25T09:00:00Z
3  easily the best i have ever had.  juicy flavor...  2000-03-13T21:15:00Z
4                                 An excellent dish.  2000-03-28T12:51:00Z

           DateModified
0  2000-01-25T21:44:00Z
1  2001-10-17T16:49:59Z
2  2000-02-25T09:00:00Z
3  2000-03-13T21:15:00Z
4  2000-03-28T12:51:00Z

COLUMN FORMAT

In [13]:
print("Recipes Column:\n")
print(recipes.columns.tolist())

print(" \n Review column\n")
print(reviews.columns.tolist())

Recipes Column:

['RecipeId', 'Name', 'AuthorId', 'AuthorName', 'CookTime', 'PrepTime', 'TotalTime', 'DatePublished', 'Description', 'Images', 'RecipeCategory', 'Keywords', 'RecipeIngredientQuantities', 'RecipeIngredientParts', 'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent', 'SaturatedFatContent', 'CholesterolContent', 'SodiumContent', 'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent', 'RecipeServings', 'RecipeYield', 'RecipeInstructions']

 Review column

['ReviewId', 'RecipeId', 'AuthorId', 'AuthorName', 'Rating', 'Review', 'DateSubmitted', 'DateModified']

DATA  INFORMATION:

In [14]:


print("===== RECIPES INFO =====")
recipes.info()

print("\n===== REVIEWS INFO =====")
reviews.info()

===== RECIPES INFO =====
<class 'pandas.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    522517 non-null  int64
 1   Name                        522517 non-null  str
 2   AuthorId                    522517 non-null  int64
 3   AuthorName                  522517 non-null  str
 4   CookTime                    439972 non-null  str
 5   PrepTime                    522517 non-null  str
 6   TotalTime                   522517 non-null  str
 7   DatePublished               522517 non-null  str
 8   Description                 522512 non-null  str
 9   Images                      522516 non-null  str
 10  RecipeCategory              521766 non-null  str
 11  Keywords                    505280 non-null  str
 12  RecipeIngredientQuantities  522514 non-null  str
 13  RecipeIngredientParts       522517 non-null  str
 14  AggregatedRating            269294 non-null  float64
 15  ReviewCount                 275028 non-null  float64
 16  Calories                    522517 non-null  float64
 17  FatContent                  522517 non-null  float64
 18  SaturatedFatContent         522517 non-null  float64
 19  CholesterolContent          522517 non-null  float64
 20  SodiumContent               522517 non-null  float64
 21  CarbohydrateContent         522517 non-null  float64
 22  FiberContent                522517 non-null  float64
 23  SugarContent                522517 non-null  float64
 24  ProteinContent              522517 non-null  float64
 25  RecipeServings              339606 non-null  float64
 26  RecipeYield                 174446 non-null  str
 27  RecipeInstructions          522517 non-null  str
dtypes: float64(12), int64(2), str(14)
memory usage: 111.6 MB

===== REVIEWS INFO =====
<class 'pandas.DataFrame'>
RangeIndex: 1401982 entries, 0 to 1401981
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReviewId       1401982 non-null  int64
 1   RecipeId       1401982 non-null  int64
 2   AuthorId       1401982 non-null  int64
 3   AuthorName     1401982 non-null  str
 4   Rating         1401982 non-null  int64
 5   Review         1401768 non-null  str
 6   DateSubmitted  1401982 non-null  str
 7   DateModified   1401982 non-null  str
dtypes: int64(4), str(4)
memory usage: 85.6 MB

In [15]:
# ============================================
# 6. MISSING VALUES
# ============================================

print("Missing values in Recipes:")
print(recipes.isnull().sum())

print("\nMissing values in Reviews:")
print(reviews.isnull().sum())

Missing values in Recipes:
RecipeId                           0
Name                               0
AuthorId                           0
AuthorName                         0
CookTime                       82545
PrepTime                           0
TotalTime                          0
DatePublished                      0
Description                        5
Images                             1
RecipeCategory                   751
Keywords                       17237
RecipeIngredientQuantities         3
RecipeIngredientParts              0
AggregatedRating              253223
ReviewCount                   247489
Calories                           0
FatContent                         0
SaturatedFatContent                0
CholesterolContent                 0
SodiumContent                      0
CarbohydrateContent                0
FiberContent                       0
SugarContent                       0
ProteinContent                     0
RecipeServings                182911
RecipeYield                   348071
RecipeInstructions                 0
dtype: int64

Missing values in Reviews:
ReviewId           0
RecipeId           0
AuthorId           0
AuthorName         0
Rating             0
Review           214
DateSubmitted      0
DateModified       0
dtype: int64

In [17]:
# random samples

display(recipes.sample(10))
display(reviews.sample(10))

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
175251,183302,Pomegranate Walnut Chicken,6357,Charishma_Ramchanda,PT1H,PT30M,PT1H30M,2006-08-27T15:32:00Z,This is also known as Fesenjam. This was the r...,character(0),...,5.2,94.6,178.2,6.9,1.1,2.6,33.5,4.0,NaN,"c(""Saute the onion in 1 tablespoons oil till i..."
51022,55142,Blackberry Brandy Glazed Beef Rounds,30022,lynda clark,PT10M,PT15M,PT25M,2003-02-28T20:02:00Z,Make and share this Blackberry Brandy Glazed B...,character(0),...,9.8,102.8,107.9,2.7,0.4,1.0,28.4,6.0,12 Beef Rounds,"c(""Sauté onions, set aside."", ""Onions, black p..."
494337,512510,Bourbon-Glazed Pork Chops and Fried Eggs,724631,KateL,PT15M,PT5M,PT20M,2014-01-23T04:52:00Z,Make and share this Bourbon-Glazed Pork Chops ...,character(0),...,12.1,338.6,816.3,8.4,0.5,7.1,47.8,4.0,NaN,"c(""BROWN SUGAR RUB."", ""In a small bowl, combin..."
154226,161603,Asparagus in Tarragon Hollandaise Sauce Good a...,102058,kiwidutch,PT10M,PT5M,PT15M,2006-03-27T15:43:00Z,"We love asparagus, especially cheap and in sea...","""https://img.sndimg.com/food/image/upload/w_55...",...,5.4,225.1,342.7,12.0,5.0,4.7,8.4,4.0,NaN,"c(""Bring large pot of salted water to boil and..."
234707,244429,Summer Harvest White Chili,168896,jennifer in new jer,PT1H30M,PT10M,PT1H40M,2007-08-04T21:42:00Z,Very tasty chili with a few ingredients not us...,character(0),...,4.3,156.6,941.0,73.4,14.1,11.7,68.0,NaN,NaN,"c(""Place all ingredients in a large spaghetti ..."
73624,78427,Billie's Cookies,111520,Slewfoot Sue,PT12M,PT20M,PT32M,2003-12-09T20:00:00Z,I promise people's eyes will roll to the back ...,"""https://img.sndimg.com/food/image/upload/w_55...",...,5.8,37.1,192.1,47.0,2.2,26.0,4.5,NaN,36 Large Cookies,"c(""In a bowl the size of a bucket, throw in ev..."
55588,59832,Strawberry Jam,81385,Nashia Fife,PT15M,PT5M,PT20M,2003-04-15T20:17:00Z,Make and share this Strawberry Jam recipe from...,"""https://img.sndimg.com/food/image/upload/w_55...",...,0.0,0.0,25.9,193.2,2.9,179.0,0.6,8.0,NaN,"c(""Wash jars and rims in hot soapy water."", ""P..."
76702,81620,Pumpkin Carrot Cake,37779,ratherbeswimmin,PT35M,PT1H,PT1H35M,2004-01-20T20:00:00Z,Make and share this Pumpkin Carrot Cake recipe...,character(0),...,13.7,97.1,628.6,99.2,3.5,75.7,9.4,12.0,NaN,"c(""Cream Cheese Frosting: Add cream cheese, bu..."
11917,15131,Crabby Mushrooms,9869,Evie3234,PT6M,PT20M,PT26M,2001-11-30T16:50:00Z,Make and share this Crabby Mushrooms recipe fr...,character(0),...,3.1,19.6,86.7,1.4,0.3,0.4,4.1,NaN,24 stuffed mushrooms,"c(""Preheat oven to 180C degrees."", ""Remove the..."
125140,131543,Grilled Cinnamon Peaches With Vanilla Yogurt,214974,TheBostonBean,PT10M,PT1H,PT1H10M,2005-07-29T10:36:00Z,Make and share this Grilled Cinnamon Peaches W...,character(0),...,1.3,8.0,29.1,39.9,3.3,36.1,3.1,NaN,NaN,"c(""In a bowl toss peaches in sugar just to coa..."

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
941858,1077902,333148,937635,lolablitz,5,"Wow, what an awesome recipe! I made it with Re...",2010-04-02T19:28:03Z,2010-04-02T19:28:03Z
1315171,1509494,224363,2266426,elizabeth1234,4,I don't follow recipes because most times I do...,2016-08-22T04:01:58Z,2016-08-22T04:01:58Z
756804,836193,114550,128047,Cherylkv,2,I must have done something wrong. By the time...,2009-03-28T00:33:11Z,2009-03-28T00:33:11Z
442575,476865,43560,361939,dulce_amore,5,these were so much fun! a very well named cook...,2007-09-10T05:57:24Z,2007-09-10T05:57:24Z
49221,54731,34087,54678,karen in tbay,5,Rated with stars when tried back in Oct/02 - j...,2003-05-29T20:52:01Z,2003-05-29T20:52:01Z
1310494,1504342,48635,2006260,dag616,1,These were biscuit-like. I'm use to fluffy pan...,2016-05-24T13:25:04Z,2016-05-24T13:25:04Z
749409,827240,48782,106506,fluffernutter,4,Liked these a lot -- I'd been looking for a sk...,2009-03-14T12:06:37Z,2009-03-14T12:06:37Z
1339892,2022613,2886,2001582873,Samantha T.,1,"I'm only young, these recipes need to be more ...",2017-06-13T20:31:28Z,2017-06-13T20:31:28Z
808216,901588,115432,191015,mandagirl,5,Perfect banana muffins! Moist and oh so good!...,2009-07-06T19:23:14Z,2009-07-06T19:23:14Z
516824,561159,44321,734020,lisamariecarter,5,Wow!,2008-01-20T11:30:45Z,2008-01-20T11:30:45Z

In [18]:
#BASIC STATS

In [28]:
# Clean column names
recipes.columns = recipes.columns.str.lower().str.strip()
reviews.columns = reviews.columns.str.lower().str.strip()

print("Recipes columns:", recipes.columns.tolist())
print("Reviews columns:", reviews.columns.tolist())

# Auto-detect recipe column
possible_recipe_cols = ['id', 'recipe_id', 'recipeid', 'rid','RecipeId']

recipe_col = None
for col in possible_recipe_cols:
    if col in recipes.columns:
        recipe_col = col
        break

if recipe_col is None:
    raise Exception("No recipe ID column found. Check column names manually.")

# Auto-detect user column
possible_user_cols = ['user_id', 'userid', 'uid','ReviewId','authorid']

user_col = None
for col in possible_user_cols:
    if col in reviews.columns:
        user_col = col
        break

if user_col is None:
    raise Exception("No user ID column found.")

print("Detected recipe column:", recipe_col)
print("Detected user column:", user_col)

# Final stats
print("Total Recipes:", recipes[recipe_col].nunique())
print("Total Users:", reviews[user_col].nunique())
print("Total Reviews:", len(reviews))

Recipes columns: ['recipeid', 'name', 'authorid', 'authorname', 'cooktime', 'preptime', 'totaltime', 'datepublished', 'description', 'images', 'recipecategory', 'keywords', 'recipeingredientquantities', 'recipeingredientparts', 'aggregatedrating', 'reviewcount', 'calories', 'fatcontent', 'saturatedfatcontent', 'cholesterolcontent', 'sodiumcontent', 'carbohydratecontent', 'fibercontent', 'sugarcontent', 'proteincontent', 'recipeservings', 'recipeyield', 'recipeinstructions']
Reviews columns: ['reviewid', 'recipeid', 'authorid', 'authorname', 'rating', 'review', 'datesubmitted', 'datemodified']
Detected recipe column: recipeid
Detected user column: authorid
Total Recipes: 522517
Total Users: 271907
Total Reviews: 1401982